### ISSUE TITLE
Exported model rotation incorrect

### ISSUE THREAD

**Issue by laconicdesigns** [jtydhr88/sd-webui-txt-img-to-3d-model#7]
In the preview and also when I import the obj into blender, I need to rotate it -90deg on the x axis.

**Comment by AugmentedRealityCat** [comment]
I discovered the exact same problem using Cinema 4d, but it's also present in the extension's own 3d viewer so it's not a surprise that it also happens in Blender.

Instead of a rotation, I am swapping the Y and Z axis at import to achieve the same result. 

Fixing this at the source directly in the extension would solve the problem for all softwares at once I suppose, including the extension's own 3d viewer. It's not just that the model is not properly oriented, but that this orientation prevents the user from rotating the object in an intuitive manner, with the camera gimballing all the time.

**Comment by jtydhr88** [comment]
please check https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/issues/11, and I will close this issue now
